//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int KategorilerID { get; set; }
        public string KategoriAdi { get; set; }
        public string Aciklama { get; set; }
    }
}
